name: 'Infrastructure tests'

on:
  pull_request:
    types: 
    - opened
    - synchronize
    - labeled

jobs:
  tflint:
    name: Terraform Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: TFLint
        uses: docker://wata727/tflint

  fmt:
    name: Code Format
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:latest
    steps:
      - uses: actions/checkout@master
      - run: terraform fmt --recursive --diff -check=true

  terratest:
    if: github.event.label.name == 'terratest'
    name: Terratest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@master
    - name: Setup Go 1.13.x
      uses: actions/setup-go@v1
      with:
        go-version: '1.13.5'
    - name: Run tests
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_INFRA_TEST_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_INFRA_TEST_SECRET_ACCESS_KEY }}
      run: |
        cd terratest/tests && go test -v -timeout 35m mlflow_test.go
